export { computerMove } from "./computerMove"
export { isTerminal } from "./isTerminal"
export { isBoardEmpty } from "./isBoardEmpty"
export { changePlayer } from "./changePlayer"
export { updateScores } from "./updateScores"
export { checkValidMove } from "./checkValidMove"
export { minimax } from "./minimax"